runtime: nodejs20
service: default
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  NODE_ENV: "production"
  GOOGLE_CLOUD_PROJECT: "ahura-posts"
  GOOGLE_CLOUD_REGION: "us-central1"

handlers:
  - url: /.*
    script: auto
    secure: always